Repository hmcts/idam-user-profile-bridge, pull requests merged in 2023-11, with the labels that each got.

#103 SIDM-8936 switch to real s2s
  charts/idam-user-profile-bridge/Chart.yaml
  charts/idam-user-profile-bridge/values.preview.template.yaml
  src/main/java/uk/gov/hmcts/idam/userprofilebridge/controllers/UserProfileController.java
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/idam/userprofilebridge/controllers/UserProfileControllerTest.java
Labels: ns:idam, prd:idam, rel:idam-user-profile-bridge-pr-103

#104 SIDM-8936 fix bearer
  src/main/java/uk/gov/hmcts/cft/rpe/api/auth/RpeS2SRequestInterceptor.java
Labels: ns:idam, prd:idam, rel:idam-user-profile-bridge-pr-104

#105 SIDM-8936 pipeline use different service id
  Jenkinsfile_CNP
Labels: ns:idam, prd:idam, rel:idam-user-profile-bridge-pr-105

#125 Suppress CVE-2023-36052
  config/owasp/suppressions.xml
Labels: ns:idam, prd:idam, rel:idam-user-profile-bridge-pr-125
