Repository hmcts/idam-user-profile-bridge, pull requests merged in 2025-04, with the labels that each got.

#524 Update Jenkinsfile_nightly
  Jenkinsfile_nightly
Labels: ns:idam, prd:idam, rel:idam-user-profile-bridge-pr-524

#534 SIDM-9754 add fortify
  Jenkinsfile_nightly
  build.gradle
  config/fortify-client.properties
Labels: ns:idam, prd:idam, rel:idam-user-profile-bridge-pr-534

#535 SIDM-9403 Dockerfile user
  Dockerfile
Labels: ns:idam, prd:idam, rel:idam-user-profile-bridge-pr-535

#538 exclude client updates
  src/main/java/uk/gov/hmcts/idam/userprofilebridge/properties/IdamBridgeTargetProperties.java
  src/main/java/uk/gov/hmcts/idam/userprofilebridge/service/UserEventService.java
  src/main/java/uk/gov/hmcts/idam/userprofilebridge/trace/TraceAttribute.java
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/idam/userprofilebridge/service/UserEventServiceTest.java
Labels: ns:idam, prd:idam, rel:idam-user-profile-bridge-pr-538
